### ISSUE TITLE
build with PYTHONQTALL_CONFIG

### ISSUE THREAD

**Issue by wangdaye078** [MeVisLab/pythonqt#211]
Qt5.15.9 +pythonqt3.4.2
set PYTHONQTALL_CONFIG=PythonQtCore PythonQtGui PythonQtNetwork PythonQtXml
qmake -o Makefile D:\Qt5\5.15\QtSources\PythonQt\PythonQt.pro
nmake
it is work fine

Qt5.15.15 +pythonqt3.5.2
use same command
PythonQt_QtAll build with none module

i edit PythonQt_QtAll.pro
CONFIG += $${PYTHONQTALL_CONFIG}
chang to:
CONFIG += $$split(PYTHONQTALL_CONFIG, " ")
it is work fine

**Comment by mrbean-bremen** [comment]
With pythonqt 3.4.2, the environment variable was ignored, and the CONFIG just used the default value, so this is not a regression, but a problem with a new feature.

@iakov - you made the fix that added support for the environment variable, can you have a look? Maybe the variable has to be defined in another way? As far as I can see, using `$$split` as done by @wangdaye078 makes sense.

**Comment by wangdaye078** [comment]
With pythonqt 3.4.2, the environment variable was not ignored.
i read the PythonQt_QtAll-Qt5-Python3.8.dll PE import directory, it Only include the modules I specified。

**Comment by mrbean-bremen** [comment]
You are right, I mis-read the history. This was already fixed in 3.4.0. In this case I don't know why it behaves differently - I don't see any change in this regard. We use cmake instead of qmake, so we did not notice that.

I think that your fix is correct anyway - maybe you can make a PR? 
Would still like to have @iakov's opinion here, and to understand what has changed.
