### ISSUE TITLE
Handling with pyc files ignores standard python flags

### ISSUE THREAD

**Issue by kreuzberger** [MeVisLab/pythonqt#41]
Hi!
During development we added the -B (DontWriteByteCode) and the environment variables for that to our execution.
PythonQt seems to ignore those flags in PythonQtImporter and writes/loads the pyc files directly.

I think the writing of pyc files NOT in __pycache__  has historical py2 reasons, but could the flag be evaluated in PythonQtImporter?
There is a function to load with standard python loader in PythonQt.h, but i seems too different to the "reqular" parseFile Method
and is not referenced by the interface to evaluate it.

Could handling of this flag be integrated? Or a PythonQt specific Flag would be also ok? Second would be better to have "normal" python behaviour of writing cache files only for imported files/modules and not during call of evalFile

**Comment by florianlink** [comment]
Yes, feel free to provide a merge request for this.

In our own projects, we stopped using the PythonQtImporter mechanism,
because the Python 3 importers have changed so much and we did not want to
reimplement all features of the default python importer again and again.
We originally did the custom importer to support crypted Python files.

So I would actually recommend switching to parseFileWithPythonLoaders

and to not enable the custom PythonQtImporter anymore. This will give you
default Python 3 imports with all flags and caching.

We could also introduce a PythonQt init flag to enable usage of
parseFileWithPythonLoaders instead wherever files are loaded (or introduce
a flag in those methods, whatever is easier).

I will not have time for this in the near future, so a merge request for
this would also be welcome!
